refreshDock: true
variables:
  jetbrains: "/Users/christoph/Library/Application Support/JetBrains/Toolbox/apps"
  icons: "/Users/christoph/Documents/Icons"
icons:
 IntelliJ: "$icons/IntelliJ.icns"
 CLion: "$icons/CLion.icns"
 DataGrip: "$icons/DataGrip.icns"
 WebStorm: "$icons/WebStorm.icns"
 Android Studio: "$icons/Android Studio.icns"
 GoLand: "$icons/GoLand.icns"
patches:
  - icon: GoLand
    app:
      folder: "$jetbrains/Goland"
      appPattern: "GoLand.*\\.app$"
      icnsPattern: "goland.icns$"

  - icon: IntelliJ
    app:
      folder: "$jetbrains/IDEA-U"
      appPattern: "IntelliJ IDEA.*\\.app$"
      icnsPattern: "idea.icns$"

  - icon: CLion
    app:
      folder: "$jetbrains/CLion"
      appPattern: "CLion.*\\.app$"
      icnsPattern: "clion.icns$"

  - icon: WebStorm
    app:
      folder: "$jetbrains/WebStorm"
      appPattern: "WebStorm.*\\.app$"
      icnsPattern: "webstorm.icns$"

  - icon: DataGrip
    app:
      folder: "$jetbrains/datagrip"
      appPattern: "DataGrip.*\\.app$"
      icnsPattern: "datagrip.icns$"
