apiVersion: v1
kind: VariableProvider
metadata:
  name: vars
spec:
  variables:
    - name: jetbrains
      value: "/Users/christoph/Library/Application Support/JetBrains/Toolbox/apps"
    - name: apps
      value: "/Applications"
    - name: icons
      value: "/Users/christoph/Documents/Icons"
---
apiVersion: v1
kind: AppProvider
metadata:
  name: apps
  components:
    - vars
spec:
  apps:
    - name: IntelliJ
      path: "$vars.jetbrains/IDEA-U"
      appPattern: "IntelliJ IDEA.*\\.app$"
      icnsPattern: "idea.icns$"
    - name: GoLand
      path: "$vars.jetbrains/Goland"
      appPattern: "GoLand.*\\.app$"
      icnsPattern: "goland.icns$"
    - name: CLion
      path: "$vars.jetbrains/CLion"
      appPattern: "CLion.*\\.app$"
      icnsPattern: "clion.icns$"
    - name: WebStorm
      path: "$vars.jetbrains/WebStorm"
      appPattern: "WebStorm.*\\.app$"
      icnsPattern: "webstorm.icns$"
    - name: DataGrip
      path: "$vars.jetbrains/datagrip"
      appPattern: "DataGrip.*\\.app$"
      icnsPattern: "datagrip.icns$"
    - name: Android Studio
      path: "$vars.jetbrains/AndroidStudio"
      appPattern: "Android Studio.*\\.app$"
      icnsPattern: "studio.icns$"
      #- name: Brave
      #icnsPath: "$vars.apps/Brave Browser.app/Contents/Resources/app.icns"
    - name: Notion
      icnsPath: "$vars.apps/Notion.app/Contents/Resources/electron.icns"
    - name: Docker 
      icnsPath: "$vars.apps/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/Resources/icon.icns"
---
apiVersion: v1
kind: IconProvider
metadata:
  name: icons
  components:
    - vars
spec:
  # Find Icons automatically in a folder based on the search pattern.
  # THe name of the Icon is the file name without the extension
  folders:
    - path: "$vars.icons"
      icnsPattern: ".*\\.icns$"
  icons:
  # Manually define a icon
  #  - name: GoLand
  #    path: "$vars.icons/GoLand.icns"

---
apiVersion: v1
kind: Patcher
metadata:
  name: patcher
  components:
    - apps
    - icons
spec:
  refreshDock: true
  dryRun: false
  # Automatically patch all apps with the icon that has the same name
  matches:
    - appProvider: apps
      iconProvider: icons
      priority: 1
  # Manually define a patch
  patches:
   - app: apps.Notion
     icon: icons.Notion4
     priority: 2
   - app: apps.Docker
     icon: icons.Docker3
     priority: 2
